name: authentication_repository
description: Dart package which manages the authentication domain.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # BLoC,
  equatable: ^2.0.0
  # Firebase,
  firebase_auth: ^1.0.2
  firebase_core: ^1.0.3
  # Google,
  google_sign_in: ^5.0.1
  # Twitter,
  webview_flutter: 2.0.0-nullsafety.4
  oauth1: 2.0.0

  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0